server:
  port: 9000

spring:
  application:
    name: microservice-auth-center
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/auth_center?characterEncoding=utf-8
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000 #连接在连接池的最小生存时间（毫秒）

  redis:
    #数据库索引
    database: 0
    host: 10.10.50.230
    port: 6379
    password: 123456
    #连接超时时间
    timeout: 5000

loginCode:
  expiration: 1 #登录验证码过期时间，单位 分钟
  prefix: login_code #验证码redis的key值前缀


mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启Mybatis下划线命名转驼峰命名



